spring:
  application:
    name: bus-hub-basic

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bh_basic
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhm-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: false
    mixed: true
    out-of-order: true
    table: schema_version

#  security:
#    strategy: MODE_INHERITABLETHREADLOCAL

#------------------------------------
# Server settings
#------------------------------------

server:
  port: 8500
  servlet:
    context-path: /api


#------------------------------------
# Logging settings
#------------------------------------

logging:
  level:
    com.pipecrafts: DEBUG